- source/partials/company/_clients.slim
https://trello.com/c/Zur8KEhV/71-bigger-text-on-company-page-mapa-mundi
> Raised font-size

- source/partials/homepage/_contact.slim
Replaces the word 'little' by 'and young'.
> Updates contacts copy

- source/javascripts/_input.es6
The radio buttons don't select any option when we first arrive at it via the keyboard.
Now they do
> Selectes radio button on first visit

- source/images/community/rubytown.svg
Source: http://stackoverflow.com/a/25837986
> Fixes Rubyconf PT background on IE

- source/stylesheets/components/_ratio_enforcer.scss
https://trello.com/c/vUDG21oI/105-clients-area-firefox
> Fixed aspect ratio on client images

- source/community.slim
- source/company.slim
- source/hire-us.slim
- source/index.slim
- source/layouts/layout.slim
- source/partials/_footer.slim
- source/partials/_nav.slim
- source/partials/homepage/_hero.slim
- source/work.slim
Changes h1 to h2 inside a footer, because it is not yet supported by all
SRs.
> Some a11y improvements

- source/partials/community/_events.slim
- source/partials/company/join-us/_apply.slim
- source/partials/work/_services.slim
- source/partials/work/product_development/_prototypes.slim
- source/stylesheets/components/_base.scss
- source/stylesheets/components/_stick_to_bottom.scss
Created an hacky component, that only makes sense if combined and used in a certain way.
Basically it needs to have the columns' height and then the bottom element is absolutely positioned.
It might become less obvious how we should use margins when playing along with this component, since it positions the element outside the container
> Fixed button alignments

- source/partials/case-studies/creators-school/2015/_conclusion.slim
- source/partials/case-studies/creators-school/2015/_gallery.slim
- source/partials/case-studies/creators-school/2015/_new_face.slim
- source/stylesheets/case-studies/creators-school/_gallery.scss
- source/stylesheets/case-studies/creators-school/_stripe.scss
- source/stylesheets/case-studies/creators-school/_superhero.scss
https://trello.com/c/PiAlcAKI/95-cs-case-study-review
> Fix CS's case study

- source/partials/case-studies/creators-school/_plug.slim
- source/stylesheets/case-studies/creators-school/_panel.scss
- source/stylesheets/components/_panel.scss
> Fixes easy money plug on CS case study

- source/javascripts/case-studies/easy-money/_animate_showcase.es6
- source/partials/case-studies/easy-money/_solution_create_voucher.slim
- source/stylesheets/case-studies/easy-money/components/_image_showcase.scss
> Fix easymoney showcase on mobile

- source/partials/homepage/_contact.slim
- source/stylesheets/components/_contacts_grid.scss
Fixes contacts alignment on safari and iOS
This solution was tested on iPhone 5 (Safari and Chrome), iPad2 (Safari and Chrome), HTC One (Android 5.1, system web view, chrome and firefox), Firefox, Safari and Chrome.
Old:
New:
> Fix contacts on safari and iOS

- source/partials/consulting/_hero.slim
- source/partials/work/product_development/_hero.slim
- source/partials/work/training/_hero.slim
> Fix margins on prdocut development, consulting and training

- source/partials/company/_team.slim
- source/partials/hire-us/_form.slim
- source/stylesheets/components/_hire_us_grid.scss
- source/stylesheets/components/_team_grid.scss
Fixes hire-us page on safari
Removes max-width from team grid in favor of horizontalGrid--limited
> Fixes hire-us page on safari

- source/community.slim
- source/company.slim
- source/company/join-us.slim
- source/hire-us.slim
- source/hire-us/success.slim
- source/index.slim
- source/partials/_newsletter.slim
- source/stylesheets/components/_base.scss
- source/stylesheets/components/_newsletter.scss
- source/work.slim
- source/work/consulting.slim
- source/work/product-development.slim
- source/work/product-development/design-sprint.slim
- source/work/product-development/mdp.slim
- source/work/training.slim
> Adds 'Subscribe to our newsletter' section, before footer.

- source/partials/_footer.slim
- source/stylesheets/case-studies/oncostats.scss
- source/stylesheets/case-studies/oncostats/_theme.scss
- source/stylesheets/case-studies/oncostats/components/_hero.scss
- source/stylesheets/case-studies/oncostats/components/_panel.scss
- source/stylesheets/case-studies/oncostats/theme/_colors.scss
- source/stylesheets/case-studies/oncostats/theme/_theme-color.scss
Why:
* It's already August, this should have been done already.
* Refactoring the pages footer to mention 2016 in the copyright text.
> Update copyright year

- source/partials/_experience.slim
- source/stylesheets/components/_clients_grid.scss
- source/stylesheets/components/_experience.scss
- source/stylesheets/utilities/_aspect-ratio.scss
- source/stylesheets/utilities/_base.scss
Using css columns instead of flexbox.
The previous approach resulted in some weird resizings that didn't look as good
> Refactors experience section

- nginx/blog.subvisual.co.conf
- nginx/groupbuddies.com.conf
- nginx/subvisual.co.conf
- nginx/test.subvisual.co.conf
Updated version of #165, which was cancelled
@pfac now it seems to be working
> Refactors nginx code and location

- source/apprenticeship/design/apply.slim
- source/apprenticeship/development/apply.slim
> Fix apprenticeship forms

- data/team.yml
> Update Laura's bio

- data/team.yml
> Update Laura's role

- source/partials/homepage/_contact.slim
Why:
* https://trello.com/c/yZCYWhDc
> Add Nick's phone number to the US contacts

- data/team.yml
Why:
* https://trello.com/c/5HUhw7vp
* Adding Helena's photo;
* Adding Helena's info to the team file.
> Add Helena

- package.json
- src/components/home/about_section.module.css
- src/components/home/about_section/icon.module.css
- src/components/home/about_section/team_subsection.module.css
- src/components/home/about_section/team_subsection/member.module.css
- src/components/home/hero_section.module.css
- src/components/home/hero_section/title.module.css
- src/components/home/ventures_section.module.css
- src/components/home/ventures_section/helping_with_subsection.module.css
- src/components/home/ventures_section/portfolio_subsection.module.css
- src/components/home/ventures_section/portfolio_subsection/venture.module.css
- src/components/home/ventures_section/universe.module.css
- src/components/layout/footer.module.css
- src/components/layout/footer/social_links.module.css
- src/components/layout/header.module.css
- src/components/load_placeholder/placeholder.module.css
Due to a problem with shell expansions of wildcards, stylelint was not applying correctly. We needed to add quotes to the path. 
This PR also applies every missing fix.
> Fix bug on stylelint script and apply fixes

- src/components/layout.js
- src/components/layout/header.module.css
- src/components/logo.js
- src/components/logo.module.css
Why:
* The blog page will use a logo with the same color as the text, but in
the main page we want to override that behaviour.
> Add color property to logo component

- src/components/home/about_section/team_subsection/member.js
- src/components/image_loader/index.module.css
- src/utils/use_window_size.js
* One of the listed issues is addressed in #240.
> Fix lint issues

- gatsby-config.js
- package.json
- yarn.lock
As suggested by @jfranciscosousa in #247.
> Add plugin to cache Gatsby build in Netlify

- src/components/layout.js
- src/components/layout.module.css
Why:
* The blog layout is completely blue, while the main page and the post
is transparent (or is white, who cares).
> Add color to the layout component

- src/components/blog/post/title.js
- src/components/blog/post/title.module.css
Why:
* Slightly different than the home page main title (smaller for
instance).
> Add blog post title component

- src/common/_custom_media.scss
- src/common/base.scss
Why:
* Because I got sick of writing the media query by hand when styling the
blog posts body. I'll refrain from changing more stuff in this PR
since we can now do massive refactoring in these styles with this
custom media and SASS nesting.
> Add custom media for desktop devices

- src/components/blog/posts_list.js
- src/components/blog/posts_list.module.scss
- src/components/blog/posts_list/entry.js
- src/components/blog/posts_list/entry.module.scss
- src/pages/blog.js
> Add blog posts list page

- src/pages/blog/posts/146-subvisual-is-hiring-a-frontend-developer.md
Migrating post from https://medium.com/subvisual/subvisual-is-hiring-a-front-end-developer-e8a8e3f2e314
> Subvisual is hiring a Front End Developer by Roberto

- src/components/layout.js
- src/components/layout.module.css
- src/pages/blog.js
Why:
* New design uses white layout for all pages.
> Use white layout in all pages

- config/plugins.js
- package.json
- src/components/blog/post/body/_iframe.scss
- src/pages/blog/posts/109-subvisual-weekly-9.md
- src/pages/blog/posts/110-subvisual-weekly-10.md
- src/pages/blog/posts/114-subvisual-weekly-12.md
- src/pages/blog/posts/115-subvisual-weekly-13.md
- src/pages/blog/posts/17-teaching-kids-how-to-code.md
- src/pages/blog/posts/21-a-toast-to-2013-welcome-2014.md
- src/pages/blog/posts/31-brace-yourselves-rubyconf-pt-is-coming.md
- src/pages/blog/posts/68-a-late-recap-of-2015.md
- yarn.lock
Why:
* There are many YouTube videos embedded in the blog posts, but these
videos are not responsive as they are;
* The spacing around the embedded videos is too small.
This change addresses these issues by:
* Adding a Remark plugin to automate embedding the videos with the
maximum width and appropriate defaults;
* Adding a plugin to wrap iframes in a responsive container;
* Changing the style for iframes in the blog post body to use the same
spacing as code blocks.
> Make embedded videos responsive

- src/pages/blog/posts/121-hakuna-matata.md
- src/pages/blog/posts/142-mirror-conf-2018.md
Why:
* Changes requested by the author.
> Fix Laura's posts intro

- package.json
- src/components/blog/post/body.js
- src/components/blog/post/body.module.scss
- src/utils/use_user_agent.js
- src/utils/user_agent_utils.js
Why:
* We increased the line height of the text body which caused the drop
cap to be slightly misaligned.
> Fix drop cap vertical position

- src/posts/2019-06-07-jobs-and-timers-in-neovim-how-to-watch-your-builds-fail.md
From Medium: https://medium.com/subvisual/jobs-and-timers-in-neovim-how-to-watch-your-builds-fail-f18931f2ffb6
> Migrate "Jobs and Timers in neovim: How to watch your builds fail" by Mendes

- src/components/blog/post/body.module.scss
> Fix drop cap in Chrome

- src/data/team_member.yaml
- src/posts/2019-06-07-jobs-and-timers-in-neovim-how-to-watch-your-builds-fail.md
- src/posts/2020-04-16-plug-based-authorisation-for-elixir-and-phoenix.md
* My twitter changed
* Shame @joaojusto
> Fix broken links all over the website

- src/posts/2020-09-11-announcing-alchemy-conf.md
This is ghost written by me, with permission and thumbs up from Roberto.
It was already reviewed by him.
> New Post: Announcing Alchemy Conf

- src/posts/2020-10-15-the-burden-of-choice/index.md
Fix 2 typos identified by readers 😃
> Fix typos in Burden of Choice post

- src/components/layout/footer/Norte2020/index.jsx
- src/components/layout/footer/Norte2020/index.module.scss
- src/components/layout/footer/social_links.module.css
- src/components/link.js
Why:
* https://3.basecamp.com/4319812/buckets/19267320/todos/3138565689#__recording_3217004939
> Fix font sizes in footer links

- package.json
- yarn.lock
These are annoying as hell.
Not really sure if they're really necessary dependencies, though?
> Fixes most peer dependency warnings

- bin/generate-post-meta-image
Finally got some time to look into this
The previous script was a bit of a mess. It "worked", but it was hard to work with once we needed to improve it
As planned, I'm now refactoring it into something we can actually look at without crying.
* adds positional arguments, solving a whole host of problems
* uses `-annotate` instead of `-draw` which allows for multiline text, and better positioning support
* merges most imagemagick calls into just a couple of them
I believe #387 is now no longer needed. In my view, it attempted to solve hacks by adding additional hacks (e.g.: using environment variables for what should be arguments)
> Refactors the banner generator into a sensible thing

- config/gatsby/plugins.js
- package.json
- yarn.lock
This file will be used by the new website on Webflow.
> Output the last blog posts to a JSON file

- static/admin/config.yml
Why:
* I want to write a blog post
* Adding my name as an author
> Add me as an author in netlify

- netlify.toml
**Why:**
- Enable the CORS header (Follow up #525)
> Add access control allow origin header

- src/components/Header/index.module.scss
- src/components/Logo/index.module.scss
- src/components/MainLayout/index.module.scss
- src/components/NavMenu/MenuClose/index.jsx
- src/components/NavMenu/MenuOpen/index.jsx
- src/components/NavMenu/index.jsx
Why:
* Design review
* Adjust paddings;
* Remove unused code;
* Add hover state to Logo;
* Change burger menu svgs;
* Small bug fix on the NavLink component
> Header tweaks

- config/node/createSchemaCustomization.js
- src/components/NewsletterCTA/index.module.scss
- src/components/PostAuthorAbout/index.jsx
- src/components/PostAuthorAbout/index.module.scss
- src/components/PostLayout/index.jsx
- src/templates/Post/index.jsx
- src/templates/Post/index.module.scss
Why:
- Closes #545 
- Update schema
- Add `<PostAuthorAbout />` & styles
- Adjust spacings to match design
> Post author about

- src/components/Header/index.module.scss
- src/components/PostLayout/index.jsx
- src/components/PostLayout/index.module.scss
- src/components/PostShareLinks/index.module.scss
- src/templates/Post/index.jsx
- src/templates/Post/index.module.scss
Why:
- Closes #547 
- Change share buttons styles;
- Move AuthorAbout to Post template
- Fix layout bug
> Share buttons

- config/gatsby/plugins.js
- package.json
- src/components/Arrows/index.jsx
- src/components/Arrows/index.module.scss
- src/components/Filter/index.jsx
- src/components/Filter/index.module.scss
- src/components/HighlightedPosts/index.js
- src/components/HighlightedPosts/index.module.scss
- src/components/PodcastList/index.jsx
- src/components/PodcastList/index.module.scss
- src/pages/blog.js
- yarn.lock
It takes the 3 last episodes of each podcast and shows them in publishing order.
> Show last podcasts

- src/data/team_member.yaml
- static/admin/config.yml
Why:
* In order to have an entry for a Post author in Netlify CMS
How:
* Adding an entry for Filipa
> Add Filipa to list of authors
