- source/partials/homepage/_hero.slim
- source/partials/work/_hero.slim
On browsers with fixed scrollbars (which take up space), the hero images were adding a small horizontal scroll on smaller resolutions (<1100px)
PS: RatioEnforcer conflicts with u-onlySmall and u-exceptSmall, since both set the `display` property, so I had to separate them
> Fixes hero width

- source/layouts/layout.slim
Improves perceived speed by loading typekit asynchronously.
Must be used with *Font Face Observer* and requires https://github.com/subvisual/blue/pull/94
Resources:
http://help.typekit.com/customer/portal/articles/6852-Controlling-the-Flash-of-Unstyled-Text-or-FOUT-using-Font-Events
> Loads Typekit asynchronously

- source/partials/case-studies/_creators-school-link.slim
- source/partials/case-studies/_easy-money-link.slim
- source/partials/case-studies/creators-school/2015/_gallery.slim
- source/stylesheets/case-studies/creators-school/_ratio-enforcer.scss
- source/stylesheets/components/_clients_grid.scss
- source/stylesheets/components/_panel.scss
- Pictures on CS case study now showing;
- CS case study gallery with correct height;
- Nav overlay on easy.money and CS case studyes withow text from background;
- Case studies links on work page with correct height; 
- Clients grid now wraps correctly;
> Safari (mac and iOS) fixes 

- Rakefile
- source/stylesheets/components/_atom.scss
Why:
* The styleguide was not showing the styles
* Stop requiring the font-awesome-sass, which we have stopped using a
while ago
* Ignoring some of the SASS special sintax in animations, which the
linter seems to dislike
> Fixes styleguide

- source/partials/case-studies/creators-school/_plug.slim
Why:
* The Creators School plug for easy.money case study was not displaying the background correctly on Firefox.
* Removing the extra `Panel` component from the root of the template.
* Adding the `Panel--easymoneyGradient` modifier to the existing `Panel`.
> Fix Creators School plug for Easy Money case study.

- source/images/homepage/hero.svg
- source/images/homepage/tools.svg
- source/images/homepage/transparency.svg
- source/index.slim
- source/javascripts/homepage/_hero_parallax.es6
- source/javascripts/homepage/_logo_tools.es6
- source/javascripts/homepage/_logo_transparency.es6
- source/partials/homepage/_hero.slim
- source/partials/homepage/_services.slim
- source/partials/homepage/_values.slim
- source/stylesheets/components/_base.scss
- source/stylesheets/components/_hover_animation.scss
Why:
We were having weird problems with SVGs on Firefox. This could be anything
from a small typo in our code to a bug in Firefox itself. After hours of
debugging, we decided to move the SVGs to object elements, which seems to work
fine as well. There are extra requests being made now, but at least it's
working
* Moving all SVGs in the homepage to an `object` tag, instead of having them inline
* Refactor the JS code for the animations to interact with the contents of the object, instead of directly in the DOM
> Fixes homepage SVGs

- source/layouts/layout.slim
As explained [here](http://www.nateberkopec.com/2015/10/21/hacking-head-tags-for-speed-and-profit.html?utm_source=Ruby+Performance+Newsletter&utm_campaign=916fde13a7-Tags_for_Fun_and_Profit10_21_2015&utm_medium=email&utm_term=0_840412962b-916fde13a7-129585657):
> if you put the viewport meta tag after your stylesheets, you will cause a layout reflow for the entire document, slowing down rendering. Don't do that. Keep your viewport tags at the top, right after your character encoding. In addition, putting a viewport tag at the bottom of the head will almost certainly cause a "flash of unstyled content" as the CSS is first loaded in the default viewport, then re-rendered in your specified viewport.
I also took the chance to do 2 other things:
* Also moved stylesheets up in. The rest are …
> μoptimizing <head>

- source/stylesheets/all.scss
- source/stylesheets/vendor/_base.scss
- source/stylesheets/vendor/_hellobar.scss
Why:
The pop-up is really annoying on mobile devices. This hides it.
> Hide hellobar on small devices

- source/stylesheets/components/_team_member.scss
Why:
* Team member photos are being rendered as 200x400, causing the images
to stretch.
This change addresses the error by:
* Limiting the height of the picture to keep it square.
> Fix team member picture

- helpers/custom_template_helpers.rb
- source/partials/_nav.slim
Depends on: https://github.com/subvisual/blue/pull/98
Why:
* The apprenticeship link should be replaced by a button linking to the
/hire-us page
> Refactor Nav

- source/stylesheets/components/_hire_us_grid.scss
- source/stylesheets/components/_radio.scss
Remove extra border in radio buttons on iOS
Why:
* We are styling radio buttons ourselves, on the `::before` pseudo element, so
any extra style should be remove. Apparently there was an extra square border
around our round radio button.
* Forcing the border on the actual input to be invisible
Fix issue with hire us form overflowing
Why:
* In Safari on small dimensions (and by extension iOS), the hire us form was
overflowing to the next panel. This was happening due to an issue with how
Safari uses flex, when compared to webkit.
* Only setting the `flex-grow` to 1 when the direction of flex is row, which is
really the only place we need it and does not mess up with Safari
> Fix iOS issues with the hire us form

- bin/setup
- package.json
Why:
* It does not specify which executable should run the script;
* It is using NPM to install bower manually instead of using a package
manifest file;
* It is installing Bower without the global option, but assuming that
the Bower executable will be available globally;
* It is installing Node dependencies after Bower dependencies.
These changes address the issues by:
* Refactoring the setup script;
* Adding Bower as a dependency to the package manifest file.
> Fix project setup script

- data/site.yml
Why:
* HelloHired.com is no more.
* Refactoring the site configuration to replace links to hellohired.com
with links to send us an e-mail.
> Replace links to HelloHired.com

- source/index.slim
- source/javascripts/all.js
- source/javascripts/homepage/_blog_posts.es6
- source/partials/homepage/_blog_posts.slim
- source/stylesheets/components/_base.scss
- source/stylesheets/components/_homepage_hero.scss
- source/stylesheets/components/_post_author.scss
- source/stylesheets/components/_section_heading.scss
Why:
In this change, I'm adding a section with the most recent blog posts to
the homepage. Because there is no back-end for this website, we decided to load the blog posts dynamically from an endpoint I recently created on the blog.
You'll notice a new component named `SectionHeading`. It uses custom font-sizes because this component is intended for aesthetics, not content. The font-size works the same way a `height` would on any other component. For that reason, I didn't make an effort to include those sizes in the system.
* Add a section for blog posts.
* Load blog posts from API and use a template to display on the screen.
> Add section with blog posts

- config.rb
- source/stylesheets/components/_case_study.scss
- source/stylesheets/components/_contacts.scss
Using BrowserStack we noticed that our landing page didn't look right in
many browsers. The main reason for that is we were only using
auto-prefixer for ie, while Firefox and Chrome still needs prefixing for
rules like `column-count`.
Another common issue is images taking more space than they are supposed
to. That was solved by limiting them to their parents with `width:
100%`. There was already a `max-width` in place, but it was not having
any effect.
> Support more browsers

- source/partials/_footer.slim
Why:
* The footer links are kind of outdated:
- The company values section was removed;
- RubyConf section in the community page refers to RubyConf 2015 and
we're doing a gap year;
- BragaRB is dead;
- We're missing links for MirrorConf, Braga.Design and Braga.Product.
* Removing the company values, RubyConf and BragaRB links;
* Adding links for Mirror Conf, Braga.Design and Braga.Product.
> Update footer links

- source/layouts/layout.slim
Why:
* Big-ass dependency with little use. We're better off.
> Remove Small Chat

- source/partials/community/_events.slim
- source/stylesheets/components/_base.scss
- source/stylesheets/components/_meetup_logo.scss
Why:
* While the logo image is visually kept with the correct dimensions, for
some reason Firefox on higher DPI screens assumes a larger width for
it, pushing the grid cells beyond their limits, overflowing the whole
website horizontally.
+ Adding a new specific component just for the Meetup logos containing
them to the correct dimensions.
> Fix community meetups section

- Gemfile
- Gemfile.lock
Why:
* Security vulnerability ([CVE-2018-3760](https://groups.google.com/forum/#!topic/ruby-security-ann/2S9Pwz2i16k)).
¯\_(ツ)_/¯
Also:
* Using `github` to fetch gems directly from the repository is not safe,
so I changed `middleman-es6` to use HTTPS instead.
> Update Sprockets version

- s3_website.yml
Why:
* The current configuration forces the use of environment variables;
* Omitting the ID and secret will cause the gem to default to looking
for the credentials in the AWS SDK default locations, thus allowing
the use of user-wide credentials and environment variables alike.
- [s3_website
README](https://github.com/laurilehmijoki/s3_website#using-standard-aws-credentials)
- [AWS SDK credentials
locations](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html)
> Remove ID and secret from s3_website config

- package.json
- src/common/useDetectJavascript.js
- src/components/LoadPlaceholder/index.js
- src/components/PageTitle/index.js
- src/components/PageTitle/index.module.css
- src/components/home/Hero/Title.js
- src/html.js
- yarn.lock
* Render the default title font while scripts are not loaded on the `Title` component
* Add noscript tag to the `LoadPlaceholder` component, rendering it's children without the loading animation if there are no scripts
* Extends `html.js` and removes the default `noscript` message (this app works well with Javascript)
> Add noscript fallbacks to Title and LoadPlaceholder

- package.json
- src/components/LoadPlaceholder/index.js
- src/components/Planet/index.js
- src/components/ViewableMonitor/index.js
- src/components/home/Ventures/Portfolio/index.js
- src/components/home/Ventures/Universe/index.js
- yarn.lock
Why:
* Apparently we're not using the recommended package for the
intersection observer with react;
* Also, we need the extra flexibility provided by
researchgate/react-intersection-observer.
* Replacing the package for the intersection observer with React;
* Refactoring the `LoadPlaceholder` and `ViewableMonitor` components to
use the new package;
* Refactoring the `Planets` component to check for its own visibility,
instead of relying on the outer components (important for animations
as only one of the planets in the same animation can be visible at any
given time).
> Replace package for intersection observer

- yarn.lock
Why:
* Apparently there's a security vulnerability on `js-yaml` prior to
version `3.13.1` (see https://github.com/nodeca/js-yaml/pull/480 for
further details);
* Upgrading `js-yaml` requires upgrading `gatsby`;
* As a general rule, it's not a good idea to linger very far behind the
base framework.
* Upgrading Gatsby and all Gatsby plugins, transformers, and directly
related dependencies to the latest compatible versions.
> Upgrade Gatsby to 2.8

- bin/setup
Why:
* ASDF is a prick with shims. You change the NodeJS version, but it
keeps the shim file as an executable, which means normal script checks
for an executable presence pass but then the shim fails because Yarn
is not installed.
* Changing the script to always try to install (or update) Yarn. A bit
slower, but idempotent aswell.
> Fix setup script on Yarn install

- package.json
- yarn.lock
Why:
* It is now above 1.0 (which means we can use semver to avoid breaking
stuff).
> Upgrade react-intersection-observer

- src/components/home/about_section.module.css
The logo was not aligned on any browser that wasn't Firefox.
> Fix logo alignment on the about section

- src/components/call_to_action.module.css
Why:
* https://trello.com/c/5vt531VP
* Increasing the border-bottom of the call_to_action to 3px;
> Increase **Together** underline by 1px

- package.json
- src/components/home/about_section/team_subsection/member.js
- src/components/home/about_section/team_subsection/member.module.css
- src/components/home/hero_section.js
- src/components/home/hero_section.module.css
- yarn.lock
in some places, we use different images between mobile and desktop.
it's not just a matter of the images having a different size, they
also have different "cuts". because the images are loaded async with JavaScript, the CSS rules that add
'display: none' to mobile images in desktop (and the other way around)
are ignored. this means that desktop and mobile images are always loaded for every request.
to solve this, there's a thing called [art
direction](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#Art_direction)
that [gatsby also supports](https://www.gatsbyjs.org/packages/gatsby-image/#art-directing-multiple-images).
extra: reduced the quality of hero-3 in desktop because it's the biggest
image in our website and it doesn't seem to change …
> stop loading both mobile and desktop images

- src/components/home/about_section/team_subsection/member.js
- src/components/layout/footer/social_links.js
Importing lodash usign `import _ from "lodash"` will import the whole
library. The correct way to import lodash is to only import the pieces
you need, for instance `import map from lodash/map`. In this case, we
simply don't need lodash in this situation, so I removed it. It's still
being used in other places, but this already removes around 70kb to the
bundle size. And because this is JS and our initial animation
requires JS to run, we can use as many optimizations as we can.
> Optimize the imports of lodash

- src/components/home/about_section/team_subsection.js
- src/components/home/hero_section.js
- src/components/home/ventures_section/portfolio_subsection.js
- src/components/layout/footer/location.js
Most images were being used in containers bigger than the ones specified
in the query. Because of this, some images weren't looking great in
retina displays.
> update images maxWidth, maxHeight and qualtiy

- src/components/layout.js
- src/components/layout/header.js
Why:
* The blog will use a slightly different logo in the header, otherwise
it should be the same header.
* Refactoring the layout header component to accept a function that
renders the logo;
* Refactoring the layout component to accept a function that renders the
header logo, falling back to the default logo component.
> Inject logo into header component

- src/components/SocialLink.js
- src/components/home/about_section.module.css
- src/components/layout/footer/location.js
- src/components/link.js
- src/components/link.module.css
Why:
* Links are currently defaulting to the "black" color, and are changed
using a component property. However their color is based on the
background, which is set by parent components. So we can instead make
links depend on text color, which is set by the same components that
change the background.
* Refactoring the link component to always use the current color;
* Refactoring the about subsection component to set the current text
color accordingly.
> Change links to use current text color

- src/components/home/about_section.js
- src/components/home/about_section/team_subsection/member.js
- src/components/layout.module.css
- src/components/layout/footer.js
- src/components/layout/footer/location.js
- src/components/text.js
- src/components/text.module.css
Why:
* We're constantly setting the text component color when it's not black,
but the default color actually depends on the background, which is set
by parent components.
* Refactoring the text component to recognize only the purple color (the
rest is actually useless at the moment);
* Refactoring the layout component to set the default text color to
black;
* Refactoring the about and footer sections not to use the color
property, which is now redundant.
> Change text component to inherit color by default

- src/common/reset.css
Why:
* Most browsers set links to blue by default, purple for visited links,
and ready when links are pressed. We most definitely don't want any of
this even by default.
> Set anchors to use current text color by default

- src/components/home/about_section/team_subsection.js
- src/data/team.yaml
Why:
* The blog will need to fetch the information of users from the team
data file, but this file is currently omitting past blog post authors.
Ideally the author information should be in the post itself to keep
things denormalized, but since it isn't, the quickest way to address
the issue is to re-add old team members, and simply add a field to
mark them as inactive, excluding them from the team page if so.
> Add support for inactive team members

- src/components/link.module.css
Why:
* Links are currently styling the text themselves, which makes it hard
for wrapping components to influence their style;
* These styles are actually useless now.
> Change links to use the current text style

- src/common/normalize.css
Why:
* The links in the top navigation bar are too small;
* Most of the content of our pages use a base font size and line heights
for the body of text, and we're gradually changing components that
simply inherit these values to do just that. The top navigation bar
was already changed accordingly.
> Set base typography sizes

- src/components/layout.js
Why:
* The blog will use new variants of the Colfax font that are not
included in the current kit.
> Update Typekit styles

- src/common/reset.css
Why:
* Blog posts are written in Markdown, and rendering them won't allow us
to set specific classes to the DOM elements. Therefore, we need to
ensure styles are as uniform and sane as possible from the start and
across browsers.
* By default blockquote elements have some spacing around, which we want
to remove.
* By default browsers underline active links in some states, which we
want to remove for consistency.
> Remove blockquote margins and link underlines

- src/data/blog_contributor.yaml
Why:
* Some blog post authors are no longer on the team, some were just
guests.
> Add blog contributors data

- src/components/home/about_section/team_subsection.js
- src/data/team_member.yaml
Why:
* Gatsby has a better mechanism for adding the information of blog
contributors, while keeping the team members file (which requires more
information) untouched.
This reverts commit b395ea0ac9dbaf782ecdab3c16e173142e495e53 (#236).
> Remove support for inactive team members

- src/data/blog_contributor.yaml
- src/data/team_member.yaml
Why:
* The blog posts identify the author by a key. In past iterations of the
blog the team member data file would have a key-value structure at the
root, where the key of authors would map to their info. Due to the way
Gatsby automatically loads the information from these files, the best
structure was for the top-level to be an array of team members
instead, which removed the key.
Now that we're adding back the blog posts, we once again need this
identifying unique key, but need to keep the array-like structure.
Therefore we add this key field.
PS: Gatsby is a prick and doesn't let me use `id`...
> Add keys to team members data

- src/components/blog/post/body_wrapper.js
- src/components/blog/post/body_wrapper.module.css
- src/components/blog/post/wrapper.js
- src/components/blog/post/wrapper.module.css
- src/components/page_wide_wrapper.js
- src/components/page_wide_wrapper.module.css
Why:
* The layout of the blog is a tricky one with 3 levels.
On the outer the content is centered with a limit to the maximum width of the design. This may or may not be padded (for instance images have to fill the entire width without side padding in mobile).
Below that level is the post content, including header and body, which has a smaller limit width and is aligned to the left inside the outer container.
Lastly, there's the body of the post, which is aligned to the right within the post container, also with a smaller width.
These containers allow the layout to responsively adapt to the entire range of widths from mobile to desktop, only causing a jump when font sizes and padding sizes have to change.
> Add wrapper components for the blog posts

- gatsby-node.js
Why:
* #251 removed the active field from team members, which required
creating a type via JavaScript API to set the default value. Which we
don't need anymore.
> Simplify GraphQL schema

- gatsby-config.js
- package.json
- src/components/call_to_action.module.css
- yarn.lock
Why:
* The styles for the blog post body (being added in #257) are more
complex than resonable mostly because, due to the Markdown rendering,
we're unable to use specific CSS classes for each rendered element,
and as such have to rely heavily on descendant selectors, which is
causing a lot of repetition.
* The issue is not specific to the blog though, and as shown with the
CTA component, this can significantly simplify the styles of some
components.
> Add PostCSS plugin for nesting CSS

- gatsby-config.js
Why:
* Gatsby generated the config file using back-ticks everywhere,
apparently because since these strings allow for interpolation they
should now be used everywhere. Anyhow, that's not our convention (yet)
at least, and this file with a different convention is rather
confusing.
> Fix quotes in Gatsby config

- src/components/blog/post/body.js
- src/components/blog/post/body.module.scss
- src/components/blog/post/body/_anchor.scss
- src/components/blog/post/body/_blockquote.scss
- src/components/blog/post/body/_bold.scss
- src/components/blog/post/body/_code.scss
- src/components/blog/post/body/_code_block.scss
- src/components/blog/post/body/_heading.scss
- src/components/blog/post/body/_horizontal_rule.scss
- src/components/blog/post/body/_image.scss
- src/components/blog/post/body/_inline_code.scss
- src/components/blog/post/body/_italic.scss
- src/components/blog/post/body/_list.scss
- src/components/blog/post/body/_paragraph.scss
Why:
* The body of a blog post will be generated from the respective Markdown
file. As such, we need to style the generated elements without being
able to set specific classes to each one.
* There are also many details here that have to tweaked all at once
since we can't split the inner parts of the Markdown document into
smaller components, such as spacings, typography, adjustments for
responsiveness, etc.
> Add blog post body component

- config/node/create_schema_customization.js
Why:
* For the blog, we'll use the `gatsby-transformer-remark`, processes and
loads all Markdown files as `MarkdownRemark` nodes.
* From these nodes, we'll need to extract not only the content, which we
want he system to infer, but also the frontmatter content, which we
know the structure and can include in the schema.
* One of the fields in the blog post schema is the author. We want the
author information to come from two distinct sources at the moment:
the team and the blog contributores, both of which are loaded through
yaml.
* Defining the structure of a post's frontmatter using an author
interface, which both blog contributors and team members have to
implement in order to correctly render the blog posts with their
information.
* This has the added …
> Extend GraphQL schema for blog

- src/pages/blog/posts/132-design-sprints-and-the-academia.md
- src/pages/blog/posts/135-super-powered-vim-part-iii-skeletons.md
Why:
* When deploying, Netlify is notifying us of insecure mixed content
being detected in our blog posts:
```
Although you have enabled HTTPS on your site, we’ve detected some content that’s still being served over an HTTP connection. Learn more about mixed content.
In blog/posts/132-design-sprints-and-the-academia/index.html:
Insecure img urls:
http://i.imgur.com/t8UHRIY.gif
In blog/posts/135-super-powered-vim-part-iii-skeletons/index.html:
Insecure img urls:
http://i.imgur.com/Efolbol.gif
```
> Fix mixed content warning in Netlify

- src/components/blog/posts_list.js
- src/components/blog/posts_list/entry.js
Why:
* Last step before #212, we need to change https://subvisual.com/blog to
dynamically retrieve the list of posts for which we generated a page.
* Changing the posts list component to query the contents processed from
Markdown files;
* Adding a formatted date field to the posts list entry component, along
with the intro in the frontmatter, and the author information.
> Dynamically fill blog posts list

- src/components/blog/post/body.module.scss
- src/components/blog/post/body/_iframe.scss
- src/pages/blog/posts/109-subvisual-weekly-9.md
Why:
* https://subvisual.com/blog/posts/109-subvisual-weekly-9/
There's an embedded YouTube video in this post that's not correctly
centered.
* Extending the blog post body component with styles for iframes;
* Updating the embedded video tag in the blog post.
> Fix iframe in blog posts body

- src/components/blog/posts_list.module.scss
- src/components/blog/posts_list/entry.js
- src/components/blog/posts_list/entry.module.scss
Why:
* New design uses our dark blue (or purple) for the title;
* The line dividing the posts entries is not using the text color.
> Fix colors in blog posts list

- src/components/blog/post/body/_blockquote.scss
Why:
* Paragraphs have top margins despite being the first element in the
block quote.
> Fix paragraph margins in blog post block quotes

- src/templates/blog/post.module.scss
Why:
* The desktop bottom margin is not being applied in production;
* There should not be any side margin, the placement is handled by the
inner wrapper components.
> Fix blog post header margins

- config/plugins.js
- package.json
- src/common/_breakpoints.scss
- src/common/_custom_media.scss
- src/common/_fonts.scss
- src/common/base.scss
- src/components/blog/post/body.module.scss
- src/components/blog/post/body/_blockquote.scss
- src/components/blog/post/body/_code_block.scss
- src/components/blog/post/body/_heading.scss
- src/components/blog/post/body/_horizontal_rule.scss
- src/components/blog/post/body/_iframe.scss
- src/components/blog/post/body/_image.scss
- src/components/blog/post/body/_list.scss
- src/components/blog/post/body/_paragraph.scss
- src/components/blog/posts_list.module.scss
- src/components/blog/posts_list/entry.module.scss
- src/components/home/hero_section/title.module.scss
- src/components/home/hero_section/title/animated_letters.module.scss
- src/components/layout/header.module.scss
- src/components/layout/header/nav_link.module.scss
- src/components/page_title.module.scss
- src/pages/index.scss
- src/templates/blog/post.module.scss
- yarn.lock
Why:
* Some custom media queries are not being correctly processed with Sass
nesting, which is causing bugs like the blog posts margins not
changing from mobile to desktop next to the footer;
* This is not the first issue we've seen where custom media queries are
not correctly processed with Sass nesting, which leads me to believe
both tools are in some way conflicting with each other.
* Replacing the PostCSS custom-media plugin with the include-media Sass
library to handle media queries;
* Replacing node-sass with dart-sass to have Map functions and better
configure include-media (this also has the advantage of not needing
`libsass` supposedly, so no binary binding hell);
* Changing `gatsby-plugin-sass`'s config to facilitate importing common
partials …
> Replace PostCSS custom-media with include-media

- src/components/image_loader/index.js
- src/components/load_placeholder/placeholder.js
Why:
* If Javascript is disabled all images loaded lazily are not shown
because the placeholder never leaves.
> Remove image placeholders on JS disabled

- src/components/blog/post/body/_blockquote.scss
- src/components/blog/post/body/_heading.scss
- src/components/blog/post/body/_list.scss
- src/components/blog/post/body/_paragraph.scss
- src/components/blog/post/body/_variables.scss
Why:
* As requested in the design.
This change addressed the need by:
* Adding a variables file to be used by the sub-styles in for the blog
post body with the new text content width values;
* Refactoring all affected content components to use the new variables
file;
* Tweaking the placement of the quote sign in blockquotes in desktop
environments.
> Change the width of the text content in blog posts

- src/components/blog/post/header.js
- src/components/blog/posts_list.js
- src/components/blog/posts_list/entry.js
- src/templates/blog/post.js
dates were being typed as `typeof(Date)`, which wasn't correct because they seem to always be passed around as a string, and only parsed on the Header component
retinaCover was marked as required, but very few posts actually have it
not sure if this the full fix, or even the correct one. happy to hear feedback
and why are we ignoring the non-retina cover altogether?
> Fixing post listing and header PropTypes

- config/plugins.js
- package-lock.json
- package.json
- src/components/blog/post/body/_image.scss
With this change, instead of creating a `my-post.md` file, we can create a structure:
```
my-post/
index.md
img.png
```
and inside, use regular markdown to include the image `![badjerous](./img.png)`
This will allow us to publish images into our posts while keeping everything encapsulated in the same folder, and without us having to manually upload files to S3
PS: I tested this my creating a sample post with an image, using the structure mentioned above. Didn't include that test code here. But trust me, it works xD
> Ability to reference filesystem images in markdown

- src/components/blog/posts_list.js
- src/components/blog/posts_list.module.scss
- src/components/blog/posts_list/entry.js
- src/pages/blog.js
- src/pages/blog.module.scss
Why:
* The posts list component is currently bound to the blog root page, and
it is currently the one querying the data to include in this page;
* We'll need to use this component in other pages, like the authors page
in preparation in #297.
* Extracting the data query to the root blog page component;
* Extracting any layout styling external to the posts list itself to the
root blog page component;
* Refactoring the posts list component to simply render the content
based on a list of posts provided as a property;
* Refactoring the posts list entry component to extract the author
information provided as a single object.
> Make posts list component page agnostic

- config/node/create_pages.js
- config/node/path_utils.js
Why:
* By default, GatsbyJS does not recognize any files automatically
besides those under `src/pages`. Those files are the manifests of each
page to be created, and any code outside those files has to be
explicitly imported somewhere in their code.
To automatically recognize any file outside `src/pages` GatsbyJS uses
the `gatsby-source-filesystem` plugin. We use this plugin to make
Gatsby aware of things like images, files with data, etc.
GatsbyJS then uses transformer plugins, such as
`gatsby-transformer-remark`, that work separately from the previous
ones. They traverse the files Gatsby is aware of and apply some
transformation to them, making this transformation available via
graphQL queries. All products of a configured transformer plugin are
made available, either as individual …
> Extract path utils

- config/node/create_pages.js
Why:
* The current query is sorting the results by date, which is completely
unnecessary since we want to generate a page for each result, and the
generation order has no impact whatsoever;
* We can use `distinct` to directly query all distinct values of a
specific field, and obtain an array with just those values, removing
the need for further destructuring.
> Optimize blog posts pages generation query

- config/node/blog_posts.js
- config/node/create_pages.js
- config/plugins.js
- gatsby-config.js
Why:
* The plugins configuration is currently a function of the root of the
project, but it is unnecessary since we know the root of the project
from the config file's location.
* #271 added a blog posts config fjile, to retain the variables related
to the blog posts relevant for the config. Since #302, only the
absolute path is being used and by a single config file, making this
external file utterly useless.
* The create pages config is using relative paths to find the blog posts
pages template.
* When producing the final path of the blog posts pages, we're using a
tool that joins the path in a system-specific way, when this should
always be using POSIX paths despite the system it runs on.
> Fix potential problems with paths in config

- src/components/blog/post/body/_inline_code.scss
Why:
* #257 added the blog post body component using Source Code Pro for code
blocks and inline code. Due to this being a larger-than-normal font,
we styled the inline code to be smaller than the current text size.
#282 changed the font size in text blocks to Inconsolata precisely for
being smaller, to give code blocks more capacity for showing up code.
However, the previous inline rule now makes the inline code too small.
> Use current text size in inline code in blog posts

- config/node/create_pages.js
- src/components/blog/post/header.js
- src/components/blog/posts_list/entry.js
- src/pages/blog.js
- src/templates/blog/author.js
- src/templates/blog/author.module.scss
- src/templates/blog/post.js
Why:
* Allows listing the blog posts of specific authors.
* Expanding the dynamic page generation logic to generate a new page for
each distinct author who wrote a blog post, similar to the root blog
page with a list of their posts;
* Refactoring blog post headers to link the author's name to the
respective page;
* Refactoring the post list component entry to accept not having the
author information in the list of posts, and not render such
information (to avoid repetition), and link the author's name to the
respective page when present.
> Add blog author pages

- config/site_metadata.js
As far as I can tell, this dotless-i thing is no longer used
This `siteMetadata.description` is only used for SEO. The title string
is hardcoded, due to the weird animation needs going on, and the
dotless-i is achieved using a specific font instead of a different
character
> Fixing site description

- src/components/blog/post/body.module.scss
Why:
* https://subvisual.com/blog/posts/continuous-stuff-with-github-actions
The drop cap in this post is misplaced in some browsers, because #306
changed the main CSS rule for the drop cap to apply to the first `p`
tag instead of the first child, but did not change the system-specific
styles accordingly.
* Changing all drop cap styles to apply to the first `p` tag.
> Fix drop cap in posts with a pre-message

- config/plugins.js
- package.json
- src/components/blog/post/body.module.scss
- src/components/blog/post/body/_image.scss
- src/components/blog/post/body/_paragraph.scss
- yarn.lock
Why:
* #305 added `gatsby-remark-images` which places images inside a
paragraph with a wrapper around it. Images added this way do not
assume the placement devised in #257.
* The placement devised in #257 relies on `gatsby-remark-unwrap-images`,
which removes the paragraph tag around the image. This made it easier
to place the images since there was no need to circumvent the styles
applied to regular text-only paragraphs.
This change addresses the issues by:
* Removing `gatsby-remark-unwrap-images`;
* Refactoring the image placement styles to unify images from remote
sources and images from the local filesystem (and thus processed by
`gatsby-remark-images`).
> Fix image placement in blog posts

- src/components/blog/post/_variables.scss
- src/components/blog/post/body.module.scss
Why:
* `gatsby-remark-images` places the images in the blog posts using
inline styles, where it automatically sets the maximum width to the
value in the plugin configuration. However, we want this value to be
slightly smaller below the desktop breakpoint, since the grid gaps
also become smaller.
* Overriding the inline styles in the images styles by using
`!important`, setting the maximum width responsively.
> Fix blog post image width

- src/common/utils/_interpolate.scss
- src/components/blog/post/body/_blockquote.scss
Why:
* #296 changed the width of the paragraphs in blog posts, which caused
block quotes to become misaligned.
* Adding an interpolation Sass mixin, to cover for cases where a
property must have a dynamic value between two breakpoints, allowing
the styles to be completely responsive without unnecessary jumps;
* Realigning the blockquote parts to align with the new text width with
full responsiveness.
Before:
After:
> Realign blog post block quotes

- package.json
- yarn.lock
`yarn outdated` says it's outdated. This fixes that.
> Upgrade intersection observer polyfill

- config/node/create_pages.js
- config/node/create_schema_customization.js
- config/node/on_create_node.js
- gatsby-node.js
- src/components/blog/post/header.js
- src/components/blog/post/header.module.css
- src/components/blog/post/header/cover.js
- src/components/blog/post/header/cover.module.scss
- src/templates/blog/post.js
- src/utils/url_utils.js
Why:
* Following #305, where we added the ability to reference images in the
local filesystem in the blog post Markdown body, our blog posts can
now be self contained, with the required images sitting next to the
blog post;
* That did not cover the blog post covers though (pun intended), which
are expected to be URLs in the blog post frontmatter.
* Post-processing all nodes created by Markdown files and adding a
`cover` node field, which is the cover URL or a path, resolving it
into an absolute path from the Markdown file directory;
* Passing the new field to the page creation context, allowing to use
this field to locate the image file in GraphQL;
* Refactoring the blog post template to extract the cover file sharp
fragment and pass it down to the blog …
> Add support for file paths in blog post covers

- src/components/blog/post/body/_blockquote.scss
- src/components/blog/post/body/_variables.scss
Why:
* I forgot to consider the side padding in #334. :grimacing:
* Fixing the text width max size considering the side padding;
* Adjusting the blockquote elements positioning to the new width.
> Fix blog post mobile text width

- config/node/on_create_node.js
- package.json
- src/components/blog/post/body/share_links.js
- src/components/blog/post/body/share_links.module.scss
- src/components/blog/post/body_wrapper.js
- src/components/blog/post/body_wrapper.module.scss
- src/components/blog/post/wrapper.js
- src/templates/blog/post.js
- src/templates/blog/post.module.scss
- yarn.lock
Why:
* As designed.
* Adding `react-share`, which seems to be the standard dependency to add
social sharing links;
* Pre-computing the URL for each blog post after the Markdown node is
created, relying on the `URL` environment variable which is set on
Netlify to use the default site name or the custom domain the site was
set up with (more info in the [Netlify docs]);
* Refactoring the wrapper components used in a blog post to accept a
custom `className` from the parent components;
* Refactoring the blog post layout to place the sharing links on the
left of the text, as designed, falling back to the vertical flow at
the end of the post in mobile.
[Netlify docs]: https://docs.netlify.com/configure-builds/environment-variables/#git-metadata
> Add share links in blog posts pages

- config/node/on_create_node.js
- src/components/seo.js
- src/templates/blog/post.js
Why:
* https://3.basecamp.com/4319812/buckets/16728109/todos/2849314582
The blog post URL is being generated using the `path` tooling from
Node.js, to ensure the slashes are placed as expected. However, `path`
does not deal well with the double slashes in an URL's protocol, and
is removing one of them, resulting in an invalid URL.
* We're always using the root URL for social networks metadata.
* Replacing this logic with the proper use of the `URL` constructor;
* Using the blog post's URL instead of the root URL for social networks
metadata, if available.
> Fix blog post URL generation

- src/components/seo.js
- src/templates/blog/post.js
Why:
* Every page in the website is using the same default image for the
social networks meta tags.
* Using the blog post's cover, if there is one.
> Use post cover for meta tag images

- config/node/create_pages.js
- config/node/create_schema_customization.js
- config/node/on_create_node.js
- src/posts/2020-02-23-apprenticeship-and-summer-camp-programs/index.md
- src/templates/blog/post.js
Most of our posts nowadays don't have a cover image.  That leads to the preview
on social media being a default banner from the homepage, which tells nothing
about the post itself.
As a monkey patch, Laura and Baila have been manually creating images for each
post, after-the-fact (e.g.:
https://twitter.com/subvisual/status/1286280282354655234)
Not only is this laborious, it also works against social engagement, because
the tweet now consists of a link + image. The image itself is not a link to the
post, making the experience confusing (and frankly, I wouldn't be surprised if
we got less views over this)
This PR allows us to specify a `seoImage` in each post, which will be used for social media,
without the need for a cover existing on the post
(This will tie in nicely with the PR draft …
> Ability to specify a meta-image for posts without a cover

- src/components/SEO/index.jsx
Why:
* #372 refactored the SEO component and introduced an issue where the
title of the homepage contains the separator that should only be
visible when there's a page-specific title.
* Extracting the title building logic to its own function in the SEO
component.
Before:
After:
> Fix SEO title

- src/components/blog/posts_list/entry.js
Why:
* Following #381 blog posts intros no longer have any HTML tags or
Markdown in them, so we can render them as a normal value.
> Stop rendering HTML in blog post intros

- src/pages/blog.js
Why:
* Some blog posts were published with the same date but are meant to
follow a certain order which can be maintained by their title.
> Order blog posts by date and title

- config/gatsby/plugins.js
- config/gatsby/plugins/rssFeed.js
- config/gatsby/siteMetadata.js
- config/node/onCreateNode.js
- package.json
- src/components/SEO/index.jsx
- src/templates/blog/post.js
- src/utils/usePathToURL.js
- src/utils/useSiteMetadata.js
- yarn.lock
Why:
* https://subvisual.slack.com/archives/C02A7GR2N/p1600641975000600
We have received some requests for a RSS feed of our blog.
* Adding the `gatsby-plugin-feed` to generate the RSS feed
automatically;
* Configuring the generation of a feed exclusively with blog posts, and
with their data properly configured;
* Refactoring the site metadata to use `siteUrl` for the root URL of the
website, since it is assumed by `gatsby-plugin-feed` and probably
other similar plugins.
> Add RSS feed to the blog

- config/gatsby/plugins/rssFeed.js
- config/node/createSchemaCustomization.js
- src/data/team_member.yaml
Why:
* https://subvisual.slack.com/archives/C02A7GR2N/p1602094908003600?thread_ts=1600641975.000600&cid=C02A7GR2N
It was a feature request from an unknown party we feel like indulging.
* Adding an email field to authors information;
* Adding a custom field to the RSS feed items with the author
information, using the company's public contact email address when the
author did not provide one;
* Adding the email address for Mendes;
https://subvisual.slack.com/archives/C02A7GR2N/p1602144829008900?thread_ts=1600641975.000600&cid=C02A7GR2N
* Adding the email address for Miguel.
https://subvisual.slack.com/archives/C02A7GR2N/p1602145455009100?thread_ts=1600641975.000600&cid=C02A7GR2N
> Add author information to the RSS feed

- package.json
- src/components/SEO/MetaTags/Keywords/index.tsx
- src/components/SEO/MetaTags/Keywords/types.d.ts
- src/components/SEO/MetaTags/OpenGraph/index.tsx
- src/components/SEO/MetaTags/OpenGraph/types.d.ts
- src/components/SEO/MetaTags/Twitter/index.tsx
- src/components/SEO/MetaTags/Twitter/types.d.ts
- src/components/SEO/MetaTags/index.tsx
- src/components/SEO/MetaTags/types.d.ts
- src/components/SEO/index.tsx
- src/components/SEO/types.d.ts
- src/utils/useSiteMetadata/index.ts
- src/utils/useSiteMetadata/types.d.ts
- tsconfig.json
- yarn.lock
Why:
* GatsbyJS now ships with full TypeScript support, which means we can
make use of it for most of the website's source code. In particular
for React components, it allows us to drop `PropTypes`, which does not
actually prevent any bad typing, in favor of TypeScript type checking
in the CI.
* Configuring the TypeScript compiler to allow for an easy conversion of
our components;
* Refactoring the SEO component as an example and showcase of the end
result with TypeScript.
> Configure TypeScript

- src/components/AnnouncementBanner/index.jsx
Why:
* https://3.basecamp.com/4319812/buckets/14602877/todos/3078612807#__recording_3180018623
We changed the link to our jobs page but forgot to update the copy,
which is still referring the blog post.
> Fix announcement banner copy

- src/components/layout/footer/Norte2020/index.module.scss
Why:
* https://3.basecamp.com/4319812/buckets/19267320/todos/3138565689#__recording_3177522445
* https://3.basecamp.com/4319812/buckets/19267320/todos/3138565689#__recording_3183123234
> Reduce text size for Norte2020 document links

- config/gatsby/plugins.js
- config/gatsby/plugins/sass.js
Why:
* By default Gatsby uses only the name of the module it gets from the
filename, which means that most of our CSS modules become
`index-something-XXXXX` when nesting all the files related to a
component in a single directory (due to CSS module files being named
`index.module.(s)css`.
* Tweaking `localIdentName` in the CSS Webpack loader so it uses the
folder in the generated class name, by prepending the folder
interpolation to the GatsbyJS default value for `localIdentName`
(copied from [the source])
[the source]: https://github.com/gatsbyjs/gatsby/blob/18c182a574475c9c06dbbeb7ddae27f5cb008fe9/packages/gatsby/src/utils/webpack-utils.ts#L216
> Refactor generated CSS module class names

- config/gatsby/plugins.js
- src/components/home/about_section/team_subsection.js
- src/components/home/hero_section.js
- src/components/home/ventures_section/portfolio_subsection.js
- src/components/layout/footer/Norte2020/index.jsx
- src/components/layout/footer/location.js
- src/templates/blog/post.js
Because modern image compression.
Before (only our homepage hero):
After:
> Adds WebP support to both sharp and remark image loaders

- config/node/createPages.js
- plugins/seo-cover/gatsby-node.js
Disabling the generation of default SEO images locally and not re-generating when they already exist changes the start time from a couple of minutes to almost instant.
> Disable default SEO images locally

- static/academy-assets/academy-fonts.css
Why:
- Homerun doesn't load font file directly, trying to force it through a CSS file (Follow up #525 and #526 )
> Academy fonts stylesheet

- src/components/Header/index.module.scss
Why:
- Closes #540 
- Change the navbar z-index to make it a higher value than the highlighted posts slider
> Change header z-index

- src/components/PostList/index.module.scss
Why:
- Author component had less opacity meaning that the Author's picture had some transparency
- Replace opacity in PostList for a color
> Replace opacity for color in PostList

- src/data/category.yaml
- src/posts/2022-04-28-how-we-nurture-a-work-life-balance-culture/index.md
- src/posts/2023-03-09-7-steps-to-a-better-company-culture/index.md
- src/posts/2023-09-05-the-power-of-company-retreats/index.md
- static/admin/config.yml
Why:
* #576
How:
* Changing the relevant occurences of `operations` to `company-building`
and `Operations` to `Company Building`
> Renaming the tag "Operations" to "Company Building"
